### PR TITLE
Set "extensionKind": "ui" to support remote development

### LINKED ISSUE #108: Set extensionKind in package.json to support Remote Development
Hi, I'm on the VS Code team. We recently released support for [Remote Development](https://code.visualstudio.com/blogs/2019/05/02/remote-development) and I noticed that your may extension need a small change to ensure users have a good experience when using it remote workspaces.

## What is the issue?
To make remote development as transparent as possible to users, VS Code distinguishes two classes of extensions:

- **UI Extensions**: These extensions make contributions to the VS Code user interface and are always run on the user's local machine. UI Extensions cannot directly access files in the workspace, or run scripts/tools installed in that workspace or on the machine. Example UI Extensions include: themes, snippets, language grammars, and keymaps.

- **Workspace Extensions**: These extensions are run on the same machine as where the workspace is located. When in a local workspace, Workspace Extensions are run on the local machine. When in a remote workspace, Workspace Extensions are run on the remote machine. Workspace Extensions can access files in the workspace to provide rich, multi-file language services, debugger support, or perform complex operations on multiple files in workspace (either themselves or by invoking scripts/tools). 

You can find more details about this architecture [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-types).

**VS Code currently infers that your extension is a Workspace Extension. This means that users who have your extension installed must also install it to the remote in order to use it in remote workspaces.** I believe that your extension should probably be a UI extension instead. That way your extension will always be enabled for users who install it, even if they open a remote workspace.

## How do I fix this?
To tell VS Code that your extension is a UI extension, just add [`"extensionKind": "ui"`](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) to your extension's package.json.

UI Extensions always run on the user's local machine, even when they open a remote workspace. 

I'll submit a PR that does this. Please let me know if you have any questions or concerns about the issue. We've also put together [a guide](https://code.visualstudio.com/api/advanced-topics/remote-extensions#testing-and-debugging-your-extension) to help you test your extension in remote workspaces

*PS: As a temporary workaround for a few popular extensions, we've automatically added your extension to an internal whitelist so that is always treated as a UI extension*

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #108. See that issue for details

Please also consider backporting this small change to the old copy of this extension as well, since that version still has many users

### CODE REVIEW

**Comment by OrangeDrangon** [comment]
Does this work because I set it with the `remote.exstensionKind` setting and it did not seem to cause it to work again.

```
{
  "remote.extensionKind": {
    "coenraads.bracket-pair-colorizer-2": "ui"
  }
}
```

**Comment by davefollett** [comment]
Looking forward to being able to use this the the Remote Development extensions.

**Comment by chevtek** [comment]
Any chance we can get this merged? I love this addon but I used Remote addon a lot and it doesn't work while using it.

**Comment by ymmt2005** [comment]
@chevtek 
You may workaround the problem by putting this in your `settings.json`.
```json
    "remote.extensionKind": {
        "coenraads.bracket-pair-colorizer-2": "ui"
    }
```

**Comment by chevtek** [comment]
@ymmt2005 Yeah I saw that in an issue thread here but it doesn't work for me. I was careful to follow the detailed steps, adding the setting locally and not installing the extension remotely. The extension still does not work when remoting.

**Comment by Stanzilla** [comment]
@CoenraadS any news here?

**Comment by CoenraadS** [comment]
The news is they moved some things to Azure Devops, and no matter what security token I generate I cannot login to vsce to update this extension :(

Kind of stumped, I can login to everything on devops, and even login to my marketplace account just fine. Only vsce doesn't cooperate.

**Comment by mjmr89** [comment]
Looks like the new version is working better, but as far as I can tell it isn't working in json or python files when connected remotely; works fine with those two when local only.

**Pull request merged**
